# Generated by Django 6.0 on 2025-12-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd10code',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
