# Generated by Django 6.0 on 2026-01-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0002_alter_icd10code_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icd10code',
            name='category_3',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='icd10code',
            name='chapter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='icd10code',
            name='chapter_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icd10code',
            name='group_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='icd10code',
            name='group_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icd10code',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
