# Generated by Django 6.0 on 2026-01-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0003_icd10code_category_3_icd10code_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icd10code',
            name='category_3',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='icd10code',
            name='chapter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='icd10code',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='icd10code',
            name='group_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
