# Generated by Django 6.0 on 2026-02-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder_app', '0004_alter_icd10code_category_3_alter_icd10code_chapter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ICD10Code',
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='extracted_text',
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='vlm_results',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
